# Generated by Django 4.2.20 on 2025-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MensajeContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
                ("asunto", models.CharField(max_length=150)),
                ("mensaje", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
