# Generated by Django 4.2.20 on 2025-09-24 05:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import proyectos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_clienteprofile_user'),
        ('servicios', '0003_remove_cotizaciondetalle_detalle_servicio_and_more'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_muestra', models.CharField(max_length=100, verbose_name='Código de Muestra')),
                ('descripcion_muestra', models.TextField(blank=True, null=True, verbose_name='Descripción de la Muestra')),
                ('id_lab', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Laboratorio')),
                ('tipo_muestra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Muestra')),
                ('masa_aprox_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Masa Aprox. (kg)')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('fecha_ensayo_rotura', models.DateField(blank=True, null=True, verbose_name='Fecha de Ensayo de Rotura')),
                ('informe', models.TextField(blank=True, null=True, verbose_name='Informe')),
                ('fecha_informe', models.DateField(blank=True, null=True, verbose_name='Fecha de Informe')),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_ANALISIS', 'En Análisis'), ('INFORME_FINAL', 'Informe Final'), ('VALIDADO', 'Validado')], default='RECIBIDA', max_length=20, verbose_name='Estado')),
                ('ensayos_a_realizar', models.TextField(blank=True, null=True, verbose_name='Ensayos a Realizar')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados_json', models.TextField(blank=True, null=True, verbose_name='Resultados del Ensayo (Descripción)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_realizacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Realización')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='proyectos.muestra', verbose_name='Muestra')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_realizados', to='trabajadores.trabajadorprofile', verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Resultado de Ensayo',
                'verbose_name_plural': 'Resultados de Ensayos',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('codigo_proyecto', models.CharField(max_length=50, unique=True, verbose_name='Código del Proyecto')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('numero_muestras', models.PositiveIntegerField(default=0, verbose_name='Número de Muestras')),
                ('numero_muestras_registradas', models.PositiveIntegerField(default=0, verbose_name='Número de Muestras Registradas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clienteprofile', verbose_name='Cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDeEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ensayo', models.CharField(max_length=100, verbose_name='Tipo de Ensayo')),
                ('fecha_entrega_programada', models.DateField(verbose_name='Fecha de Entrega Programada')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='proyectos.muestra', verbose_name='Muestra')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Orden de Ensayo',
                'verbose_name_plural': 'Órdenes de Ensayo',
            },
        ),
        migrations.AddField(
            model_name='muestra',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='DocumentoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('archivo_original', models.FileField(blank=True, null=True, upload_to=proyectos.models.documento_file_path, verbose_name='Archivo Escaneado Original (PDF/Imagen)')),
                ('resumen_ejecutivo_ia', models.TextField(blank=True, null=True, verbose_name='Resumen Ejecutivo (IA)')),
                ('analisis_detallado_ia', models.TextField(blank=True, null=True, verbose_name='Análisis Detallado (IA)')),
                ('recomendaciones_ia', models.TextField(blank=True, null=True, verbose_name='Recomendaciones (IA)')),
                ('firma_supervisor', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del Supervisor')),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas_clientes/', verbose_name='Firma del Cliente')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_finales', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Documento Final',
                'verbose_name_plural': 'Documentos Finales',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='muestra',
            unique_together={('proyecto', 'codigo_muestra')},
        ),
    ]
