# Generated by Django 4.2.20 on 2025-08-12 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import proyectos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('servicios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_muestra', models.CharField(max_length=100, unique=True, verbose_name='Código de la Muestra')),
                ('descripcion_muestra', models.TextField(verbose_name='Descripción de la Muestra')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción')),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación Física en el Laboratorio')),
                ('condiciones_recepcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condiciones de Recepción (Ej. Refrigerado, sellado)')),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Lote')),
                ('peso_volumen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso/Volumen de la Muestra')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida (Ej. g, ml, kg)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('detalles_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.detalleservicio', verbose_name='Detalles del Servicio Asociado')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados_json', models.JSONField(blank=True, null=True, verbose_name='Resultados del Ensayo (JSON)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_realizacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Realización')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='proyectos.muestra', verbose_name='Muestra')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_realizados', to='trabajadores.trabajadorprofile', verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Resultado de Ensayo',
                'verbose_name_plural': 'Resultados de Ensayos',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('descripcion_proyecto', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50, verbose_name='Estado del Proyecto')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Estimada')),
                ('fecha_finalizacion_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización Real')),
                ('notificado_cliente', models.BooleanField(default=False, verbose_name='Notificado al Cliente')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('procesado_ia', models.BooleanField(default=False, verbose_name='Procesado por IA')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clientes.clienteprofile', verbose_name='Cliente')),
                ('cotizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizacion', verbose_name='Cotización Asociada')),
                ('servicios_usados', models.ManyToManyField(related_name='proyectos_usados', to='servicios.servicio', verbose_name='Servicios Usados')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDeEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(max_length=50, unique=True, verbose_name='Código de la Orden')),
                ('tipo_ensayo', models.CharField(max_length=100, verbose_name='Tipo de Ensayo')),
                ('norma_ensayo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Norma de Ensayo')),
                ('fecha_entrega_programada', models.DateField(verbose_name='Fecha de Entrega Programada')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('estado_avance', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('ATRASADO', 'Atrasado'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado de Avance')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_ensayo', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('supervisor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_supervisadas', to='trabajadores.trabajadorprofile', verbose_name='Supervisor Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Ensayo',
                'verbose_name_plural': 'Órdenes de Ensayo',
                'ordering': ['fecha_entrega_programada'],
            },
        ),
        migrations.AddField(
            model_name='muestra',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='proyectos.ordendeensayo', verbose_name='Orden de Ensayo'),
        ),
        migrations.CreateModel(
            name='DocumentoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('archivo_original', models.FileField(blank=True, null=True, upload_to=proyectos.models.documento_file_path, verbose_name='Archivo Escaneado Original (PDF/Imagen)')),
                ('resumen_ejecutivo_ia', models.TextField(blank=True, null=True, verbose_name='Resumen Ejecutivo (IA)')),
                ('analisis_detallado_ia', models.TextField(blank=True, null=True, verbose_name='Análisis Detallado (IA)')),
                ('recomendaciones_ia', models.TextField(blank=True, null=True, verbose_name='Recomendaciones (IA)')),
                ('firma_supervisor', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del Supervisor')),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas_clientes/', verbose_name='Firma del Cliente')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_finales', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Documento Final',
                'verbose_name_plural': 'Documentos Finales',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='muestra',
            unique_together={('orden', 'codigo_muestra')},
        ),
    ]
