# Generated by Django 4.2.20 on 2025-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='condiciones_recepcion',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='detalles_servicio',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='peso_volumen',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='ubicacion_fisica',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='muestra',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='ensayos_a_realizar',
            field=models.TextField(blank=True, null=True, verbose_name='Ensayos a realizar'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='estado',
            field=models.CharField(choices=[('EN CURSO', 'En curso'), ('EN REVISIÓN', 'En revisión'), ('ENVIADO', 'Enviado')], default='EN CURSO', max_length=50, verbose_name='Estado de la Muestra'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='fecha_ensayo_rotura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ensayo (solo ensayos de rotura a la compresión)'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='fecha_informe',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Informe'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='id_lab',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID del Laboratorio'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='informe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Informe'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='masa_aprox_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Masa Aproximada (kg)'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='tipo_muestra',
            field=models.CharField(default='Sin tipo', max_length=50, verbose_name='Tipo de Muestra (Ej. Concreto, Suelo)'),
        ),
    ]
