# Generated by Django 4.2.20 on 2025-09-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clienteprofile_user'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo_voucher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Voucher/Operación'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_proyecto',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='monto_cotizacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de la Cotización'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clientes.clienteprofile', verbose_name='Cliente'),
        ),
    ]
