# Generated by Django 4.2.20 on 2025-09-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('proyectos', '0002_proyecto_codigo_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeensayo',
            name='estado_orden',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Inicio'), ('EN_PROCESO', 'En Proceso de Ensayo'), ('RESULTADOS_REGISTRADOS', 'Resultados Registrados'), ('REVISADA', 'Revisada/Cerrada')], default='PENDIENTE', max_length=50, verbose_name='Estado de la Orden'),
        ),
        migrations.AddField(
            model_name='ordendeensayo',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='trabajadores.trabajadorprofile', verbose_name='Técnico Asignado'),
        ),
    ]
