# Generated by Django 4.2.20 on 2025-08-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_muestra_condiciones_recepcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='cliente_nombre',
        ),
    ]
