# Generated by Django 4.2.20 on 2025-08-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_remove_muestra_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoensayo',
            name='resultados_json',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados del Ensayo (Descripción)'),
        ),
    ]
