# Generated by Django 4.2.20 on 2025-09-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_resultadoensayo_resultados_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo_voucher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del Voucher'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='monto_cotizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la Cotización'),
        ),
    ]
