# Generated by Django 4.2.20 on 2025-09-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyecto_codigo_voucher_proyecto_monto_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='numero_muestras_total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
