# Generated by Django 4.2.20 on 2025-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("cv", models.FileField(upload_to="bolsa_trabajo/cv/")),
                ("mensaje", models.TextField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
