# Generated by Django 4.2.20 on 2025-04-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bolsa_trabajo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OportunidadTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                (
                    "archivo_bases",
                    models.FileField(
                        blank=True, null=True, upload_to="oportunidades_trabajo/"
                    ),
                ),
                ("descripcion", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("publicado", "Publicado"),
                            ("pendiente", "Pendiente"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
