# Generated by Django 4.2.20 on 2025-08-12 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oferta', models.CharField(max_length=50, unique=True, verbose_name='Número de Oferta')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social del Cliente')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC del Cliente')),
                ('persona_contacto', models.CharField(max_length=255, verbose_name='Persona de Contacto')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo Electrónico del Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Contacto')),
                ('forma_pago', models.CharField(choices=[('POR ADELANTADO', 'Por adelantado'), ('PORCENTUAL', 'XX% por adelantado y XX% previo a la entrega'), ('POSTERIOR', 'Posterior a la conformidad del servicio')], default='POR ADELANTADO', max_length=50, verbose_name='Forma de Pago')),
                ('validez_oferta_dias', models.PositiveIntegerField(default=30, verbose_name='Validez de la Oferta (días)')),
                ('plazo_entrega_dias', models.PositiveIntegerField(default=0, verbose_name='Plazo de Entrega (días hábiles)')),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=20, verbose_name='Estado de la Cotización')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clienteprofile', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabajadores.trabajadorprofile', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cotización de Servicio',
                'verbose_name_plural': 'Cotizaciones de Servicios',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Servicio')),
                ('imagen', models.ImageField(upload_to='servicios/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio Web',
                'verbose_name_plural': 'Servicios Web',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Detalle')),
                ('descripcion', models.TextField(verbose_name='Descripción del Detalle')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/detalles/', verbose_name='Imagen')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio',
                'verbose_name_plural': 'Detalles de Servicios',
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cotizacion', to='servicios.cotizacion', verbose_name='Cotización')),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.detalleservicio', verbose_name='Detalle del Servicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
            },
        ),
    ]
