# Generated by Django 4.2.20 on 2025-09-02 22:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='ruc',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='und',
            field=models.CharField(default='und', max_length=50),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.clienteprofile'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='correo_contacto',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(choices=[('Contado', 'Al Contado'), ('15_dias', 'A 15 días'), ('30_dias', 'A 30 días'), ('3_meses', 'A 3 meses')], default='Contado', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_oferta',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='persona_contacto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='plazo_entrega_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono_contacto',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='validez_oferta_dias',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='vouchers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='servicios.cotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='metodos',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='servicios.metodo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='normas',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='servicios.norma'),
        ),
    ]
