# Generated by Django 4.2.20 on 2025-09-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_metodo_norma_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='detalle_servicio',
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='metodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.metodo', verbose_name='Método'),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.norma', verbose_name='Norma de Ensayo'),
        ),
    ]
