# Generated by Django 4.2.20 on 2025-08-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor de Laboratorio'), ('TECNICO', 'Técnico de Laboratorio')], default='TECNICO', max_length=20, verbose_name='Rol')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores_fotos/', verbose_name='Foto')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Perfil de LinkedIn')),
                ('firma_electronica', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Electrónica')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Trabajador',
                'verbose_name_plural': 'Perfiles de Trabajadores',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
