# Generated by Django 4.2.20 on 2025-05-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("foto", models.ImageField(upload_to="trabajadores_fotos/")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("linkedin", models.URLField(blank=True)),
            ],
        ),
    ]
