# Generated by Django 4.2.20 on 2026-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Trabajadores'},
        ),
        migrations.AddField(
            model_name='trabajador',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Posición en la web'),
        ),
    ]
