# Generated by Django 4.2.20 on 2026-05-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_cargo_alter_trabajador_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['cargo__orden', 'orden', 'nombre'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo_fk',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='trabajadores.cargo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Posición del trabajador dentro de su cargo'),
        ),
    ]
