# Generated by Django 4.2.20 on 2026-05-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_alter_trabajador_options_remove_trabajador_cargo_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden del área en la web')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área Organizacional',
                'verbose_name_plural': 'Áreas Organizacionales',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['area__orden', 'orden', 'nombre'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['cargo__area__orden', 'cargo__orden', 'orden', 'nombre'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden del cargo dentro del área'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='trabajadores.cargo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden dentro del cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='trabajadores.areaorganizacional'),
        ),
    ]
