# Generated by Django 4.2.20 on 2025-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="nosotros/"),
                ),
            ],
        ),
    ]
