# Generated by Django 4.2.20 on 2026-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certificado', 'Certificado'), ('politica', 'Política'), ('otro', 'Otro')], default='politica', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de portada o miniatura del documento.', null=True, upload_to='nosotros/documentos/imagenes/')),
                ('archivo', models.FileField(help_text='Subir PDF del certificado, política u otro documento.', upload_to='nosotros/documentos/archivos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Marcar si deseas priorizar este documento entre los primeros visibles.')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento de Nosotros',
                'verbose_name_plural': 'Documentos de Nosotros',
                'ordering': ['orden', '-destacado', '-creado'],
            },
        ),
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name': 'Nosotros', 'verbose_name_plural': 'Nosotros'},
        ),
    ]
