# Generated by Django 4.2.20 on 2026-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0003_tipodocumentonosotros_alter_documentonosotros_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentonosotros',
            name='archivo',
            field=models.FileField(help_text='Subir PDF, imagen, Word, Excel o PowerPoint.', upload_to='nosotros/documentos/archivos/'),
        ),
    ]
